# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x08\x63ontract\"\xde\x01\n\x0fGenerateRequest\x12\x10\n\x08workload\x18\x01 \x01(\t\x12\x15\n\rprompt_tokens\x18\x02 \x01(\x05\x12\x15\n\routput_tokens\x18\x03 \x01(\x05\x12\x16\n\x0ekv_transfer_ms\x18\x04 \x01(\x05\x12\x10\n\x08queue_ms\x18\x05 \x01(\x05\x12\x15\n\rprefill_scale\x18\x06 \x01(\x01\x12\x14\n\x0c\x64\x65\x63ode_scale\x18\x07 \x01(\x01\x12\x13\n\x0bstall_after\x18\x08 \x01(\x05\x12\x10\n\x08stall_ms\x18\t \x01(\x05\x12\r\n\x05model\x18\n \x01(\t\"2\n\x05\x43hunk\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\x0e\n\x06tokens\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\"\xda\x01\n\x06Ledger\x12\x10\n\x08\x61\x64mit_ms\x18\x01 \x01(\x01\x12\x10\n\x08queue_ms\x18\x02 \x01(\x01\x12\x12\n\nprefill_ms\x18\x03 \x01(\x01\x12\r\n\x05kv_ms\x18\x04 \x01(\x01\x12\x16\n\x0e\x66irst_token_ms\x18\x05 \x01(\x01\x12\x11\n\tdecode_ms\x18\x06 \x01(\x01\x12\x10\n\x08\x64\x65tok_ms\x18\x07 \x01(\x01\x12\x12\n\nout_tokens\x18\x08 \x01(\x05\x12\x0f\n\x07ttft_ms\x18\t \x01(\x01\x12\x0f\n\x07tpot_ms\x18\n \x01(\x01\x12\x16\n\x0etpot_median_ms\x18\x0b \x01(\x01\"#\n\rLedgerRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t2}\n\tInference\x12\x38\n\x08Generate\x12\x19.contract.GenerateRequest\x1a\x0f.contract.Chunk0\x01\x12\x36\n\tGetLedger\x12\x17.contract.LedgerRequest\x1a\x10.contract.Ledgerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=30
  _globals['_GENERATEREQUEST']._serialized_end=252
  _globals['_CHUNK']._serialized_start=254
  _globals['_CHUNK']._serialized_end=304
  _globals['_LEDGER']._serialized_start=307
  _globals['_LEDGER']._serialized_end=525
  _globals['_LEDGERREQUEST']._serialized_start=527
  _globals['_LEDGERREQUEST']._serialized_end=562
  _globals['_INFERENCE']._serialized_start=564
  _globals['_INFERENCE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
