# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"l\n\x0cInferRequest\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11max_output_tokens\x18\x02 \x01(\x05\x12\x18\n\x10tokens_per_chunk\x18\x03 \x01(\x05\x12\x10\n\x08workload\x18\x04 \x01(\t\"o\n\nInferChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0ftokens_in_chunk\x18\x02 \x01(\x05\x12\x13\n\x0b\x63hunk_index\x18\x03 \x01(\x05\x12\x13\n\x0bt_server_ms\x18\x04 \x01(\x01\x12\x10\n\x08\x66inished\x18\x05 \x01(\x08\x32H\n\tInference\x12;\n\x05Infer\x12\x17.inference.InferRequest\x1a\x15.inference.InferChunk\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=30
  _globals['_INFERREQUEST']._serialized_end=138
  _globals['_INFERCHUNK']._serialized_start=140
  _globals['_INFERCHUNK']._serialized_end=251
  _globals['_INFERENCE']._serialized_start=253
  _globals['_INFERENCE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
