# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0ctailsampling\"r\n\x0fGenerateRequest\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x10\n\x08stall_at\x18\x03 \x01(\x05\x12\x10\n\x08stall_ms\x18\x04 \x01(\x05\x12\x10\n\x08workload\x18\x05 \x01(\t\"C\n\x05\x43hunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0e\n\x06tokens\x18\x03 \x01(\x05\x12\r\n\x05\x66inal\x18\x04 \x01(\x08\x32M\n\tInference\x12@\n\x08Generate\x12\x1d.tailsampling.GenerateRequest\x1a\x13.tailsampling.Chunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=33
  _globals['_GENERATEREQUEST']._serialized_end=147
  _globals['_CHUNK']._serialized_start=149
  _globals['_CHUNK']._serialized_end=216
  _globals['_INFERENCE']._serialized_start=218
  _globals['_INFERENCE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
